# Generated by Django 4.2.7 on 2024-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicleimage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
