# Generated by Django 4.2.7 on 2024-05-05 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
